version: 2.1

env: &env
  environment:
    HOMEBREW_CACHE: /Users/distiller/.cache/Homebrew
    HOMEBREW_DEBUG: "1"
    HOMEBREW_DEVELOPER: "0"
    HOMEBREW_MAKE_JOBS: 16
    HOMEBREW_NO_ANALYTICS: "1"
    HOMEBREW_NO_AUTO_UPDATE: "1"
    HOMEBREW_NO_INSTALL_CLEANUP: "1"
    HOMEBREW_VERBOSE: "1"

commands:
  build-llvm:
    steps:
      - run:
          name: Show kernel versions
          command: |
            uname -a
            sw_vers
            xcodebuild -version
            system_profiler SPHardwareDataType

      - run:
          name: mkdir HOMEBREW_CACHE directory and touch linkage.json
          command: |
            mkdir -p $HOMEBREW_CACHE
            touch /Users/distiller/.cache/Homebrew/linkage.json

      - restore_cache:
          name: Restore Homebrew cache
          keys:
            - homebrew-{{ checksum "/Users/distiller/.cache/Homebrew/linkage.json" }}
      - run:
          name: Upgrade Homebrew formulas
          command: |
            brew upgrade --display-times
      - save_cache:
          name: Save Homebrew cache
          key: homebrew-{{ checksum "/Users/distiller/.cache/Homebrew/linkage.json" }}
          paths: "/Users/distiller/.cache/Homebrew"

      - run:
          name: Install dependency tools from homebrew
          command: |
            brew list
            brew install https://github.com/Homebrew/homebrew-core/raw/master/Formula/binutils.rb   || true
            brew install https://github.com/Homebrew/homebrew-core/raw/master/Formula/cmake.rb      || true
            brew install https://github.com/Homebrew/homebrew-core/raw/master/Formula/doxygen.rb    || true
            brew install https://github.com/Homebrew/homebrew-core/raw/master/Formula/gnu-tar.rb    || true
            brew install https://github.com/Homebrew/homebrew-core/raw/master/Formula/libxml2.rb    || true
            brew install https://github.com/Homebrew/homebrew-core/raw/master/Formula/ninja.rb      || true
            brew install https://github.com/Homebrew/homebrew-core/raw/master/Formula/pkg-config.rb || true
            brew install https://github.com/Homebrew/homebrew-core/raw/master/Formula/protobuf.rb   || true
            brew install https://github.com/Homebrew/homebrew-core/raw/master/Formula/sphinx-doc.rb || true
            brew install https://github.com/Homebrew/homebrew-core/raw/master/Formula/swig.rb       || true
            # brew link --force libffi libxml2 sphinx-doc
            # pip3 install -U pip setuptools

      - run:
          name: Generate lldb_codesign to Keychain
          command: |
            ./scripts/codesign.bash lldb_codesign
            rm -f ./lldb_codesign.*

      - run:
          name: Install LLVM toolchain via Homebrew
          command: |
            brew tap zchee/formula
            brew install zchee/formula/llvm-toolchain --build-from-source --ignore-dependencies

      - run:
          name: Compress compiled LLVM toolchain
          working_directory: ~/src/tarballs
          command: |
            gtar -czf ~/src/tarballs/llvm-dist-$(echo $CIRCLE_BRANCH | tr '._/' '-' | tr '[:upper:]' '[:lower:]')-$CIRCLE_BUILD_NUM.tar.gz /usr/local/Cellar/llvm-toolchain/9.0.0

      - store_artifacts:
          path: ~/src/tarballs

jobs:
  xcode-10-3:
    macos:
      xcode: "10.3.0"
    <<: *env
    working_directory: ~/src/github.com/zchee/circleci-darwin-build
    shell: /bin/bash -eu -o pipefail
    steps:
      - checkout
      - build-llvm
  xcode-11-0:
    macos:
      xcode: "11.0.0"
    <<: *env
    working_directory: ~/src/github.com/zchee/circleci-darwin-build
    shell: /bin/bash -eu -o pipefail
    steps:
      - checkout
      - build-llvm
  xcode-11-1:
    macos:
      xcode: "11.1.0"
    <<: *env
    working_directory: ~/src/github.com/zchee/circleci-darwin-build
    shell: /bin/bash -eu -o pipefail
    steps:
      - checkout
      - build-llvm

workflows:
  version: 2
  build-llvm:
    jobs:
      # - xcode-10-3:
      #     context: org-global
      - xcode-11-0:
          context: org-global
      # - xcode-11-1:
      #     context: org-global
